global:
  scrape_interval: 15s # Set the scrape interval to 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'llm-proxy'
    scrape_interval: 5s
    static_configs:
      - targets: ['llm-proxy:8080']